<?php
/**
*
* @package phpBB 3.1.8- Available Board-wide template variables
* @copyright (c) 2016 3Di (Marco T.)
* @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
*
*/
// The following are all _common_ variables that may be used at any point in a template.

SITENAME
SITE_DESCRIPTION
PAGE_TITLE
SCRIPT_NAME
LAST_VISIT_DATE
LAST_VISIT_YOU
CURRENT_TIME
TOTAL_USERS_ONLINE
LOGGED_IN_USER_LIST
RECORD_USERS

PRIVATE_MESSAGE_COUNT
CURRENT_USER_AVATAR
CURRENT_USERNAME_SIMPLE
CURRENT_USERNAME_FULL
UNREAD_NOTIFICATIONS_COUNT
NOTIFICATIONS_COUNT
U_VIEW_ALL_NOTIFICATIONS
U_MARK_ALL_NOTIFICATIONS
U_NOTIFICATION_SETTINGS
S_NOTIFICATIONS_DISPLAY

// Switches
S_USER_NEW_PRIVMSG
S_USER_UNREAD_PRIVMSG
S_USER_NEW

// Variouses
SID
_SID
SESSION_ID
ROOT_PATH
BOARD_URL

// Languages
L_LOGIN_LOGOUT
L_INDEX
L_SITE_HOME
L_ONLINE_EXPLAIN

// Urls
U_PRIVATEMSGS
U_RETURN_INBOX
U_MEMBERLIST
U_VIEWONLINE
U_LOGIN_LOGOUT
U_INDEX
U_SEARCH
U_SITE_HOME
U_REGISTER
U_PROFILE
U_USER_PROFILE
U_MODCP
U_FAQ
U_SEARCH_SELF
U_SEARCH_NEW
U_SEARCH_UNANSWERED
U_SEARCH_UNREAD
U_SEARCH_ACTIVE_TOPICS
U_DELETE_COOKIES
U_CONTACT_US
U_TEAM
U_TERMS_USE
U_PRIVACY
U_RESTORE_PERMISSIONS
U_FEED

// Switches
S_USER_LOGGED_IN
S_AUTOLOGIN_ENABLED
S_BOARD_DISABLED
S_REGISTERED_USER
S_IS_BOT
S_USER_LANG
S_USER_BROWSER
S_USERNAME
S_CONTENT_DIRECTION
S_CONTENT_FLOW_BEGIN
S_CONTENT_FLOW_END
S_CONTENT_ENCODING
S_TIMEZONE
S_DISPLAY_ONLINE_LIST
S_DISPLAY_SEARCH
S_DISPLAY_PM
S_DISPLAY_MEMBERLIST
S_NEW_PM
S_REGISTER_ENABLED
S_FORUM_ID
S_TOPIC_ID

S_LOGIN_ACTION
S_LOGIN_REDIRECT

S_ENABLE_FEEDS
S_ENABLE_FEEDS_OVERALL
S_ENABLE_FEEDS_FORUMS
S_ENABLE_FEEDS_TOPICS
S_ENABLE_FEEDS_TOPICS_ACTIVE
S_ENABLE_FEEDS_NEWS

S_LOAD_UNREADS

S_SEARCH_HIDDEN_FIELDS

// Templates paths
T_ASSETS_VERSION
T_ASSETS_PATH
T_THEME_PATH
T_TEMPLATE_PATH
T_SUPER_TEMPLATE_PATH
T_IMAGES_PATH
T_SMILIES_PATH
T_AVATAR_PATH
T_AVATAR_GALLERY_PATH
T_ICONS_PATH
T_RANKS_PATH
T_UPLOAD_PATH
T_STYLESHEET_LINK
T_STYLESHEET_LANG_LINK
T_JQUERY_LINK

// Switch
S_ALLOW_CDN

T_THEME_NAME
T_THEME_LANG_NAME
T_TEMPLATE_NAME
T_SUPER_TEMPLATE_NAME
T_IMAGES
T_SMILIES
T_AVATAR
T_AVATAR_GALLERY
T_ICONS
T_RANKS
T_UPLOAD

// Guess..
SITE_LOGO_IMG
